TallerIV/TallerIV/Models/EstadisticaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using TallerIV.Dominio.RangoEstadisitica;

namespace TallerIV.Models
{
    public class EstadisticaViewModel
    {
        [Required]
        public string TituloAviso;
        //public int TotalReclutador;
        public float PorcentajeApRec;
        public float PorcentajeDesRec;
        //public int TotalPostulante;
        public float PorcentajeApPost;
        public float PorcentajeDesPost;
        public List<RangoEstadistica> RangosEstadistica = new List<RangoEstadistica>();    
    }
}

TallerIV/TallerIV/Controllers/AvisoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TallerIV.Datos;
using TallerIV.Dominio;
using TallerIV.Negocio.Servicios;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using TallerIV.Dominio.Coincidencias;
using TallerIV.Dominio.Usuarios;
using System.Data.SqlClient;
using System.Configuration;
using TallerIV.Dominio.RangoEstadisitica;
using TallerIV.Models;

namespace TallerIV.Controllers
{
    [Authorize(Roles = "Empresa,Reclutador")]
    public class AvisoController : Controller
    {
        private AvisosService avisoService;
        private UsuarioReclutadorService reclutadorService;
        private AvisoSPService avisoSPService;
        public AvisoController()
        {
            avisoService = new AvisosService();
            reclutadorService = new UsuarioReclutadorService();
            avisoSPService = new AvisoSPService();
        }

        // GET: Aviso
        public ActionResult Index()
        {
            List<Aviso> avisos;
            string id = this.User.Identity.GetUserId();

            if (User.IsInRole("Empresa"))
            {
                avisos = this.avisoService.GetAllByEmpresa(id, false).ToList();
                ViewBag.UsuarioReclutador = reclutadorService.GetAllByEmpresa(id);
            }

            else
                avisos = this.avisoService.GetAllByReclutador(id, false).ToList();
            return View(avisos);
        }

        // GET: Aviso/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Aviso aviso = this.avisoService.GetById(id.Value);
            if (aviso == null)
            {
                return HttpNotFound();
            }
            return View(aviso);
        }

        // GET: Aviso/Create
        public ActionResult Create()
        {
            ViewBag.Nombre = "asda";
            return View();
        }
        // GET: Aviso/ReasignarAviso/5
        public ActionResult ReasignarAviso(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Aviso aviso = this.avisoService.GetById(id.Value);
            if (aviso == null)
            {
                return HttpNotFound();
            }
            UsuarioReclutadorService servicioReclutador = new UsuarioReclutadorService();
            List<UsuarioReclutador> Reclutadores = servicioReclutador.GetAllByEmpresa(aviso.UsuarioEmpresa_Id).ToList();
            ViewBag.Aviso = aviso;
            if (Reclutadores == null)
            {
                return HttpNotFound();
            }
            return View(Reclutadores);
        }

        [HttpPost]
        public ActionResult ReasignarAviso(long id, string Aid){
            //OPCION 1
            //TallerIVDbContext db = new TallerIVDbContext();
            //UsuarioReclutador reclutador = db.IdentityUsers.Find(Aid);
            //Aviso aviso = db.Avisos.Find(id);
            //avisoService.ReasignarAviso(aviso, reclutador);


            //OPCION 3
            avisoService.ReasignarAviso(id, Aid);

            return RedirectToAction("Index");
        }
        // POST: Aviso/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Aviso aviso)
        {
            if (ModelState.IsValid)
            {
                aviso.UsuarioReclutador_Id = this.User.Identity.GetUserId();

                BaseService<UsuarioEmpresa> usuarioEmpresaService = new BaseService<UsuarioEmpresa>();
                UsuarioEmpresa empresa = usuarioEmpresaService.GetAll().FirstOrDefault(x => x.Reclutadores.Any(r => r.Id == aviso.UsuarioReclutador_Id));
                aviso.UsuarioEmpresa_Id = empresa.Id;
                aviso.UsuarioEmpresa_Nombre = empresa.RazonSocial;
                this.avisoService.AddEntity(aviso);
                return RedirectToAction("Index");
            }
            return View(aviso);
        }

        // GET: Aviso/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Aviso aviso = this.avisoService.GetById(id.Value);
            if (aviso == null)
            {
                return HttpNotFound();
            }
            return View(aviso);
        }

        // POST: Aviso/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Titulo,Descripcion,FechaInicio,FechaFin,UsuarioReclutador_Id,UsuarioEmpresa_Id,UsuarioReclutadorAsignado_Id")] Aviso aviso)
        {
            if (ModelState.IsValid)
            {
                this.avisoService.UpdateEntity(aviso);
                return RedirectToAction("Index");
            }
            return View(aviso);
        }

        // GET: Aviso/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Aviso aviso = this.avisoService.GetById(id.Value);
            if (aviso == null)
            {
                return HttpNotFound();
            }
            return View(aviso);
        }
        //GET: Aviso/Estadisticas/5
        public ActionResult Estadisticas(long id)
        {
            Aviso aviso = this.avisoService.GetById(id);

            int PostulantesQueAprobaron = avisoSPService.AprobacionesDeUsuarios((int)id);
            int PostulantesQueDesaprobaron = avisoSPService.DesaprobacionesDeUsuarios((int)id);
            float PorcentajeAprobadosPostulante = avisoSPService.CalcularPorcentaje(PostulantesQueAprobaron, PostulantesQueDesaprobaron);
            float PorcentajeDesaprobadosPostulante = avisoSPService.CalcularPorcentaje(PostulantesQueDesaprobaron, PostulantesQueAprobaron);

            //Consulta para la cantidad de aprobaciones que tiene un Aviso.
            //No hace falta, actualmente Estadistica calculo esto apartir del Aviso.
            //cmd.CommandText = "SELECT COUNT(UsuarioEmpleado_Id) as TOTAL from AvisoUsuariosEmpleadosAprobados WHERE Aviso_Id = @query";
            //Consulta para cantidad de Postulantes que aprobaron el aviso.
            //cmd.CommandText = "SELECT COUNT(UsuarioEmpleado_Id) as TOTAL from UsuarioEmpleadoAviso WHERE Aviso_Id = @query";

            float PorcentajeAprobadosReclutador = avisoSPService.CalcularPorcentaje(aviso.UsuariosEmpleadoAprobados.Count(), aviso.UsuariosEmpleadoDesaprobados.Count());
            float PorcentajeDesaprobadosReclutador = avisoSPService.CalcularPorcentaje(aviso.UsuariosEmpleadoDesaprobados.Count(), aviso.UsuariosEmpleadoAprobados.Count());         

            List<RangoEstadistica> rangoEstadistica = avisoSPService.PorcentajeDePuntos((int)id);

            EstadisticaViewModel vista = new EstadisticaViewModel { TituloAviso = aviso.Titulo, PorcentajeApPost = PorcentajeAprobadosPostulante*100, PorcentajeDesPost = PorcentajeDesaprobadosPostulante*100, PorcentajeApRec = PorcentajeAprobadosReclutador*100, PorcentajeDesRec = PorcentajeDesaprobadosReclutador*100, RangosEstadistica = rangoEstadistica };

            return View(vista);
        }
        // GET: HomeEmpleado
        public ActionResult BuscarPostulantes(long id)
        {
            TallerIVDbContext db = new TallerIVDbContext();
            BaseService<UsuarioEmpleado> usuarioService = new BaseService<UsuarioEmpleado>(db);
            IQueryable<UsuarioEmpleado> queryEmpleados = usuarioService.GetAll();
            Aviso aviso = db.Avisos.Where(x => x.Id == id).FirstOrDefault();
            GeneradorCoincidencias generadorCoincidencias = new GeneradorCoincidencias();
            List<Coincidencia> coincidenciasList = generadorCoincidencias.GenerarListadoCoincidencias(aviso, queryEmpleados);
            ViewBag.Aviso = aviso;
            ViewBag.CantidadEncuentros = db.Encuentros.Count(x => x.Aviso_Id == aviso.Id);
            return View(coincidenciasList);
        }

        public JsonResult Like(string id, long aid)
        {
            try
            {
                bool huboEncuentro = false;
                string uid = this.User.Identity.GetUserId();
                TallerIVDbContext db = new TallerIVDbContext();
                AprobadorPostulante postulanteAprobado = new AprobadorPostulante();
                UsuarioEmpleado empleado = db.Users.OfType<UsuarioEmpleado>().Where(x => x.Id == id).FirstOrDefault();
                Aviso aviso = db.Avisos.Where(x => x.Id == aid).FirstOrDefault();
                Encuentro encuentro = postulanteAprobado.Aprobar(empleado, aviso);
                if (encuentro != null) {
                    db.Encuentros.Add(encuentro);
                    huboEncuentro = true;
                }
                db.SaveChanges();
                return Json(new { error = false, message = "Aprobación exitosa", encuentro = huboEncuentro }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(new { error = true, message = "No pudo aprobarse el aviso. Vuelva a intentarlo." }, JsonRequestBehavior.AllowGet);
            }

        }
        public JsonResult DisLike(string id, long aid)
        {
            try
            {

TallerIV/TallerIV/Views/Aviso/BuscarPostulante.cshtml
@model List<TallerIV.Dominio.Coincidencia>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutProui.cshtml";
}

<div class="row">
    <div class="header-section">
        <div class="row">
            <!-- Main Title (hidden on small devices for the statistics to fit) -->
            <!--<div class="col-md-4 col-lg-7">
                <h1>Bienvenido </h1>
            </div>-->
            <!-- END Main Title -->
            <!-- Top Stats -->
            <div class="col-md-4 col-lg-8">
                @foreach (var item in Model)
                {
                    <div id="@item.Empleado.Id">
                        <br />
                        <br />Nombre:  @item.Empleado.Nombre
                        <br />Apellido:  @item.Empleado.Apellido
                        <br />Fecha de nacimiento:  @item.Empleado.FechaDeNacimiento
                        <br />Edad:  @item.Empleado.Edad
                        <br />Descripcion:  @item.Aviso.Descripcion

                        @foreach (var aptitud in item.Empleado.Aptitud)
                        {
                            if (aptitud != null)
                            {
                                <br />@aptitud.Titulo
                            }
                        }
                        <br />Horas de trabajo:  @item.Empleado.Busqueda.HorasTrabajo
                        <br />Relacion labora:  @item.Empleado.Busqueda.TipoRelacionDeTrabajo
                        <br />Sueldo ofrecido: @item.Empleado.Busqueda.SueldoMinimo
                        <br />
                        <button onclick="LlamarLike(@item.Aviso.Id,@item.Empleado.Id)">Like!</button>
                        <button onclick="LlamarDisLike(@item.Aviso.Id,@item.Empleado.Id)">Dislike</button>
                        <br />
                        <br />
                        <br />
                        <br />
                    </div>
                }
            </div>
            <!-- END Top Stats -->
        </div>
    </div>
    <!-- For best results use an image with a resolution of 2560x248 pixels (You can also use a blurred image with ratio 10:1 - eg: 1000x100 pixels - it will adjust and look great!) -->
</div>

<script>
    function LlamarLike(ida, id)
    {
        alert("like!");
        $.ajax({
            // edit to add steve's suggestion.
            //url: "/ControllerName/ActionName",
            url: '/Aviso/Like/',
            data: { 
                id: id, 
                aid: ida
            },
            success: (data) => {
                // your data could be a View or Json or what ever you returned in your action method
                // parse your data here
                if(!data.error){
                    alert(data.message);
                    $("#" + id).remove();
                }else{
                    alert(data.message);
                }
            },
            error: function(req, status, errorObj) {
                alert('error');
            }
        });
    }
    function LlamarDisLike(id)
    {
        alert("DisLike");
        $.ajax({
            // edit to add steve's suggestion.
            //url: "/ControllerName/ActionName",
            url: '/Aviso/DisLike/',
            data: { 
            id: id, 
            aid: ida
        },
            success: (data) => {
                // your data could be a View or Json or what ever you returned in your action method
                // parse your data here
                if(!data.error){
                    alert(data.message);
                    $("#" + id).remove();
                }else{
                    alert(data.message);
                }
            },
            error: function(req, status, errorObj) {
                alert('error');
            }
        });
    }
</script>

TallerIV/TallerIV/Views/Aviso/BuscarPostulantes.cshtml
@model List<TallerIV.Dominio.Coincidencia>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutProui.cshtml";
}

<div class="content-header">
    <div class="header-section">
        <h1>
            <i class="fa fa-briefcase"></i>@ViewBag.Aviso.Titulo<br><small>Búsqueda de postulantes</small>
        </h1>
    </div>
</div>
<div class="row">
    <div>
        <div class="col-lg-12">
            @foreach (var item in Model)
            {
                <div class="col-md-6 postulante" id="@item.Empleado.Id" hidden>
                    <!-- Advanced Active Theme Color Widget Alternative -->
                    <div class="widget">
                        <div class="widget-advanced widget-advanced-alt">
                            <!-- Widget Header -->
                            <div class="widget-header text-center themed-background-dark">
                                <div class="widget-options-left">
                                    <button class="btn btn-lg btn-success" data-toggle="tooltip" title="" data-original-title="Aprobar" onclick="LlamarLike(@item.Aviso.Id,'@item.Empleado.Id')"><i class="fa fa-thumbs-o-up"></i></button>
                                </div>
                                <div class="widget-options">
                                    <button class="btn btn-lg btn-danger" data-toggle="tooltip" title="" data-original-title="Desaprobar" onclick="LlamarDisLike(@item.Aviso.Id,'@item.Empleado.Id')"><i class="fa fa-thumbs-o-down"></i></button>
                                </div>
                                <a href="#">
                                    <img src="/Content/themes/proui/img/placeholders/avatars/avatar2.png" alt="avatar" class="widget-image img-circle">
                                </a>
                                <h4 class="widget-content-light">
                                    <a href="#">@item.Empleado.Nombre @item.Empleado.Apellido</a><br />
                                    <a style="font-size:12px;" href="#" onclick="bootbox.alert('@item.Empleado.CartaDePresentacion')">Ver carta de presentación</a><br>
                                    @*<small><i class="gi gi-pin"></i> New York</small>*@
                                </h4>
                            </div>
                            <!-- END Widget Header -->
                            <!-- Widget Main -->
                            <div class="widget-main">
                                <div class="row text-center">
                                    <div class="col-lg-12"><h3 style="margin-top:0px;">Coincidencia @item.Porcentaje%</h3></div>
                                    @*<div class="col-lg-6"></div>*@
                                </div>
                                <div class="list-group remove-margin">
                                    <div class="list-group-item">
                                        <span class="pull-right"><strong>@item.Empleado.Edad</strong></span>
                                        <h4 class="list-group-item-heading remove-margin">@*<i class="fa fa-heart fa-fw"></i>*@Edad</h4>
                                        <p class="list-group-item-text"></p>
                                    </div>
                                </div>
                                <div class="list-group remove-margin">
                                    <div class="list-group-item">
                                        <span class="pull-right">
                                            <strong>
                                                @{
                                                    var aptitudes = String.Join(", ", item.Empleado.Aptitud.Select(x => x.Titulo));
                                                    <text>
                                                        @aptitudes
                                                    </text>
                                                }
                                            </strong>
                                        </span>
                                        <h4 class="list-group-item-heading remove-margin">Aptitudes</h4>
                                        <p class="list-group-item-text"></p>
                                    </div>
                                </div>
                                <div class="list-group remove-margin">
                                    <div class="list-group-item">
                                        <span class="pull-right">
                                            <strong>
                                                @item.Empleado.Busqueda.HorasTrabajo
                                            </strong>
                                        </span>
                                        <h4 class="list-group-item-heading remove-margin">Horas de trabajo deseadas</h4>
                                        <p class="list-group-item-text"></p>
                                    </div>
                                </div>
                                <div class="list-group remove-margin">
                                    <div class="list-group-item">
                                        <span class="pull-right">
                                            <strong>
                                                @item.Empleado.Busqueda.TipoRelacionDeTrabajo
                                            </strong>
                                        </span>
                                        <h4 class="list-group-item-heading remove-margin">Relación de trabajo deseada</h4>
                                        <p class="list-group-item-text"></p>
                                    </div>
                                </div>
                            </div>
                            <!-- END Widget Main -->
                        </div>
                    </div>
                    <!-- END Advanced Active Theme Color Widget Alternative -->
                </div>
            }
            <div class="col-lg-6">
                <div class="col-sm-6 col-lg-6">
                    <!-- Widget -->
                    <a href="#" class="widget widget-hover-effect1">
                        <div class="widget-simple">
                            <div class="widget-icon pull-left themed-background-spring animation-fadeIn">
                                <i class="fa fa-thumbs-o-up"></i>
                            </div>
                            <h3 class="widget-content text-right animation-pullDown">
                                <strong><span id="usuariosEmpleadoAprobados">@ViewBag.Aviso.UsuariosEmpleadoAprobados.Count</span></strong>
                                <small>Aprobaciones</small>
                            </h3>
                        </div>
                    </a>
                    <!-- END Widget -->
                </div>
                <div class="col-sm-6 col-lg-6">
                    <!-- Widget -->
                    <a href="#" class="widget widget-hover-effect1">
                        <div class="widget-simple">
                            <div class="widget-icon pull-left themed-background-fire animation-fadeIn">
                                <i class="fa fa-thumbs-o-down"></i>
                            </div>
                            <h3 class="widget-content text-right animation-pullDown">
                                <strong><span id="usuariosEmpleadoDesaprobados">@ViewBag.Aviso.UsuariosEmpleadoDesaprobados.Count</span></strong>
                                <small>Desprobaciones</small>
                            </h3>
                        </div>
                    </a>
                    <!-- END Widget -->
                </div>
                <div class="col-sm-6 col-lg-6">
                    <!-- Widget -->
                    <a href="@Url.Action("Index", "EncuentrosReclutador")" class="widget widget-hover-effect1">
                        <div class="widget-simple">
                            <div class="widget-icon pull-left themed-background-autumn animation-fadeIn">
                                <i class="fa fa-group"></i>
                            </div>
                            <h3 class="widget-content text-right animation-pullDown">
                                <strong><span id="encuentros">@ViewBag.CantidadEncuentros</span></strong><br>
                                <small>Encuentros</small>
                            </h3>
                        </div>
                    </a>
                    <!-- END Widget -->
                </div>
                
                <div class="col-sm-6 col-lg-6">
                    <!-- Widget -->
                    <a href="#" class="widget widget-hover-effect1">
                        <div class="widget-simple">
                            <div class="widget-icon pull-left themed-background-amethyst animation-fadeIn">
                                <i class="gi gi-envelope"></i>
                            </div>
                            <h3 class="widget-content text-right animation-pullDown">
                                <strong>0</strong>
                                <small>Mensajes</small>
                            </h3>
                        </div>
                    </a>
                    <!-- END Widget -->
                </div>
                
            </div>
        </div>
    </div>
</div>

<script>
    function mostrarNuevo() {
        var divAviso = $('.postulante').first();
        divAviso.show();
    }
    function LlamarLike(ida, id)
    {
        $.ajax({
            // edit to add steve's suggestion.
            //url: "/ControllerName/ActionName",
            url: '/Aviso/Like/',
            data: { 
                id: id, 
                aid: ida
            },
            success: (data) => {
                // your data could be a View or Json or what ever you returned in your action method
                // parse your data here
                if(!data.error){
                    $("#" + id).fadeOut(300, function() { 
                        $(this).remove();
                        if (data.encuentro) {
                            bootbox.alert("Se ha generado un encuentro! Ingrese al menú Mis Encuentros para ver los datos de contacto o iniciar una conversación con el postulante.");
                            var encuentros = parseInt($('#encuentros').text()) + 1;
                            $('#encuentros').text(encuentros);
                        }
                        var aprobados = parseInt($('#usuariosEmpleadoAprobados').text()) + 1;
                        $('#usuariosEmpleadoAprobados').text(aprobados);
                        mostrarNuevo();
                    });
                    //$("#" + id).remove();
                }else{
                    bootbox.alert(data.message);
                }
            },
            error: function(req, status, errorObj) {
                alert('error');
            }
        });
    }
    function LlamarDisLike(ida,id)
    {
        $.ajax({
            // edit to add steve's suggestion.
            //url: "/ControllerName/ActionName",
            url: '/Aviso/DisLike/',
            data: { 
            id: id, 
            aid: ida
        },
            success: (data) => {
                // your data could be a View or Json or what ever you returned in your action method
                // parse your data here
                if(!data.error){
                    $("#" + id).fadeOut(300, function() { 
                        $(this).remove();
                        var desaprobados = parseInt($('#usuariosEmpleadoDesaprobados').text()) + 1;
                        $('#usuariosEmpleadoDesaprobados').text(desaprobados);
                        mostrarNuevo();
                    });
                }else{
                    alert(data.message);
                }
            },
            error: function(req, status, errorObj) {
                alert('error');
            }
        });
    }
    $(function(){
        mostrarNuevo();
    });
</script>

TallerIV/TallerIV/Views/Aviso/Delete.cshtml
@model TallerIV.Dominio.Aviso

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Aviso</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UsuarioReclutador.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UsuarioReclutador.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaInicio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaInicio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaFin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaFin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UsuarioEmpresa_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UsuarioEmpresa_Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UsuarioReclutadorAsignado_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UsuarioReclutadorAsignado_Id)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TallerIV/TallerIV/Views/Aviso/Index.cshtml
@model IEnumerable<TallerIV.Dominio.Aviso>

@{
    ViewBag.Title = "Listado de avisos";
    Layout = "~/Views/Shared/_LayoutProui.cshtml";
}

<div class="content-header">
    <div class="header-section">
        <h1>
            <i class="gi gi-align_left"></i>Listado de avisos
        </h1>
    </div>
</div>
<p>
    @Html.ActionLink("Crear nuevo", "Create")
</p>
<table class="table">
    <tr>
        @*Poner nombre y apelido*@
        <th>
            Reclutador
        </th>
        <th>
            Título
        </th>
        <th>
            Fecha de inicio
        </th>
        <th>
            Fecha de fin
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @(item.UsuarioReclutador.Nombre + " " + item.UsuarioReclutador.Apellido)
        </td>
        <td>
            @item.Titulo
        </td>
        <td>
            @item.FechaInicio.ToShortDateString()
        </td>
        <td>
            @(item.FechaFin.HasValue ? item.FechaFin.Value.ToShortDateString() : "")
        </td>
        <td>
            @*@Html.ActionLink("Editar", "Edit", new { id=item.Id }) |*@
            @Html.ActionLink("Busqueda de postulantes", "BuscarPostulantes", new { id = item.Id }) |
            @Html.ActionLink("Reasignar Aviso", "ReasignarAviso", new { id = item.Id }) |
            @Html.ActionLink("Detalle", "Details", new { id=item.Id }) |
            @Html.ActionLink("Eliminar", "Delete", new { id=item.Id }) |
            @Html.ActionLink("Estadisticas", "Estadisticas", new { id = item.Id })
        </td>
    </tr>
}
</table>

TallerIV/TallerIV/Views/Aviso/ReasignarAviso.cshtml
@model IEnumerable<TallerIV.Dominio.UsuarioReclutador>

@{
    ViewBag.Title = "ReasignarAviso";
    Layout = "~/Views/Shared/_LayoutProui.cshtml";
}

<div class="content-header">
    <div class="header-section">
        <h1>
            <i class="gi gi-align_left"></i>Reasignar Aviso: @ViewBag.Aviso.Titulo
        </h1>
    </div>
</div>
<br>
<h3>Listado de Reclutadores disponibles</h3>
@using (Html.BeginForm("ReasignarAviso", "Aviso", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{ 
    <table class="table">
        <thead>
            <tr>
                <th>
                    Nombre
                </th>
                <th>
                    Apellido
                </th>
                <th>
                    Nombre de Usuario
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <input type="radio" name="Aid" value ="@item.Id" id="radio1"  />
                        <label for="radio1">@item.Nombre</label>
                    </td>
                    <td>
                        @item.Apellido
                    </td>
                    <td>
                        @item.UserName
                    </td>
                </tr>
                }
        </tbody>
    </table>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Reasignar" />
        </div>
    </div>
}